/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 20b96455489dd57c6e68ca1c7f65ed04)
interface __BaseEnv_Env {
	ACCOUNT_ISSUER: "";
	ACCOUNT_AUDIENCE: "";
	ACCOUNT_JWKS_URL: "";
	STORE_COUPONS: DurableObjectNamespace<import("./src/worker").StoreCoupons>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "StoreCoupons";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCOUNT_ISSUER" | "ACCOUNT_AUDIENCE" | "ACCOUNT_JWKS_URL">> {}
}
